### ISSUE TITLE
Infinite loop in `parseInvalidSource`

### ISSUE THREAD

**Issue by jystic** [dan-t/hsimport#10]
In some situations I found that `parseInvalidSource` loops forever.

I haven't put up a PR because I'm not 100% confident in the fix, but this seems to be working for me: https://github.com/jystic/hsimport/commit/9aa61e5a01f9fb8b86692cba3f0d35b35ef331d0

I can't give you the file that had the problem unfortunately, but the cause was putting a call to a function on a line all by itself:

```
-- imports

pure

data Foo = Foo
```

GHC thinks `pure` is part of some template haskell, or something like that.

**Comment by dan-t** [comment]
Thanks!

I think this functions needs a robust stop criterium. I now added one with dan-t@bcfdf9b.
Can you please verify if this also solved your issue?

**Comment by dan-t** [comment]
hsimport 0.6.7 is out having this change.
