### ISSUE TITLE
Here's how to allow non-cabal users to `stack install hsimport`

### ISSUE THREAD

**Issue by metaleap** [dan-t/hsimport#13]
Tried to `stack install` this so I don't have to keep a Cabal installation around just for playing with `hsimport`.. it gets stuck with this:

    directory version 1.3.0.0 found
        - hsimport requires >=1.2.0.1 && <1.3

Does it *have* to be under 1.3 or can we up this? Experimentally I set it higher in `hsimport.cabal` in my local clone of this repo and after then running simply `stack init` (or was it `stack setup`.. I just fired away all I memorized at the terminal =) to generate `stack.yaml` from your `hsimport.cabal`,  now `stack install` proceeds just fine and the program builds/installs successfully.

Stack is quite the popular alternative to cabal, so why not apply this simple tweak to your `hsimport.cabal`! Since it's already on Stackage (apparently), anyone can then `stack install hsimport` just as with most of the other popular dev-helper tools

**Comment by dan-t** [comment]
`hsimport 0.8.3` should now allow `directory 1.3`.
