### ISSUE TITLE
Add hiding parameter to import 

### ISSUE THREAD

**Issue by fendor** [dan-t/hsimport#17]
Example:
```bash
> hsimport -m "Data.Text" --hiding "length"
import Data.Text hiding (length)
```

I would be happy to implement such a feature for hsimport if this is still in the scope of hsimport!

**Comment by dan-t** [comment]
On Mon, May 27, 2019 at 04:40:18AM -0700, fendor wrote:
> Example:
> 
> > hsimport -m "Data.Text" --hiding "length"
> import Data.Text hiding (length)
> 
> I would be happy to implement such a feature for hsimport if this is still in the scope of hsimport!

Sounds fine. Just go for it!

I think the way to go would be:
- extend the 'SymbolImport' data with a 'HidingOfSymbol' data constructor
- pattern match for 'HidingOfSymbol' on the 'importChanges' function
- implement a 'hidingSymbol' function similar to the 'importModuleWithSymbol' function
